// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCecUzz1Xi86xemWjur1Kwbf8W1pvP6d4',
    appId: '1:307426584956:android:d32f95b39b52c0c66d5cf9',
    messagingSenderId: '307426584956',
    projectId: 'storyverse-db8a5',
    databaseURL: 'https://storyverse-db8a5-default-rtdb.firebaseio.com',
    storageBucket: 'storyverse-db8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZLgn4MjZMtIe-CR1aAR9_PDbsV_YPS4',
    appId: '1:307426584956:ios:b53548ce4d00a45a6d5cf9',
    messagingSenderId: '307426584956',
    projectId: 'storyverse-db8a5',
    databaseURL: 'https://storyverse-db8a5-default-rtdb.firebaseio.com',
    storageBucket: 'storyverse-db8a5.firebasestorage.app',
    androidClientId: '307426584956-kjuk1k5d10e5tob7qljoiqighej5h8uc.apps.googleusercontent.com',
    iosClientId: '307426584956-rtvrp69ljnrn814rd8dar7if6l7ufo2g.apps.googleusercontent.com',
    iosBundleId: 'com.orangepi.teranovel.teranovel',
  );
}
